/**
 * File Bridge — .shiba/ Materialization
 * ======================================
 * Generates readable markdown files from database memories.
 * These files are the interface between Shiba's DB and AI agents.
 *
 * Files generated:
 *   .shiba/user.md      — User identity, preferences, expertise
 *   .shiba/feedback.md  — Active corrections and guidelines
 *   .shiba/project.md   — Project context, decisions, architecture
 *   .shiba/skills.md    — Learned patterns and conventions
 *   .shiba/context.md   — Recent session activity and episodes
 *
 * Not LLM-generated — just formatted SQL query results.
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { resolve } from "path";
import { recall, type Memory } from "./recall.js";

const SHIBA_DIR = ".shiba";

interface MaterializeOptions {
  projectPath?: string;
  outputDir?: string;  // defaults to projectPath/.shiba or cwd/.shiba
}

function formatMemory(m: Memory, includeScore = false): string {
  const score = includeScore ? ` (relevance: ${Number(m.relevance).toFixed(2)})` : "";
  // Surface timestamp so LLM can reason about time
  const date = m.created_at ? ` _(${new Date(m.created_at).toLocaleDateString()})_` : "";
  return `- **${m.title}**${date}: ${m.content.slice(0, 300)}${score}`;
}

function formatMemories(memories: Memory[], header: string, description: string): string {
  let md = `# ${header}\n\n`;
  md += `> ${description}\n`;
  md += `> Auto-generated by Shiba Memory. Do not edit — changes will be overwritten.\n\n`;

  if (memories.length === 0) {
    md += "_No memories in this category yet._\n";
    return md;
  }

  for (const m of memories) {
    md += formatMemory(m) + "\n";
  }

  md += `\n---\n_${memories.length} memories | Last updated: ${new Date().toISOString()}_\n`;
  return md;
}

async function generateUserFile(projectPath?: string): Promise<string> {
  const memories = await recall({
    query: "user identity preferences expertise background",
    type: "user",
    limit: 15,
    project: projectPath,
    skipTouch: true,
  });

  return formatMemories(
    memories,
    "About the User",
    "Identity, preferences, and expertise. Shiba uses this to personalize responses.",
  );
}

async function generateFeedbackFile(projectPath?: string): Promise<string> {
  const memories = await recall({
    query: "corrections feedback guidelines don't always never",
    type: "feedback",
    limit: 15,
    project: projectPath,
    skipTouch: true,
  });

  return formatMemories(
    memories,
    "Feedback & Corrections",
    "Active corrections and guidelines from the user. Follow these strictly.",
  );
}

async function generateProjectFile(projectPath?: string): Promise<string> {
  const memories = await recall({
    query: "project context decisions architecture goals",
    type: "project",
    limit: 15,
    project: projectPath,
    skipTouch: true,
  });

  return formatMemories(
    memories,
    "Project Context",
    "Decisions, goals, and context for the current project.",
  );
}

async function generateSkillsFile(projectPath?: string): Promise<string> {
  const memories = await recall({
    query: "learned patterns conventions best practices skills",
    type: "skill",
    limit: 15,
    project: projectPath,
    skipTouch: true,
  });

  return formatMemories(
    memories,
    "Learned Skills & Patterns",
    "Patterns learned from past sessions. These transfer across projects.",
  );
}

async function generateContextFile(projectPath?: string): Promise<string> {
  const memories = await recall({
    query: "recent session activity events",
    type: "episode",
    limit: 10,
    project: projectPath,
    skipTouch: true,
  });

  return formatMemories(
    memories,
    "Recent Context",
    "Recent session activity and events. Expires automatically.",
  );
}

/**
 * Generate all .shiba/ files for a project.
 * Returns the output directory path.
 */
export async function materialize(opts: MaterializeOptions = {}): Promise<{
  dir: string;
  files: string[];
  totalMemories: number;
}> {
  const baseDir = opts.outputDir || opts.projectPath || process.cwd();
  const shibaDir = resolve(baseDir, SHIBA_DIR);

  // Create .shiba/ directory
  if (!existsSync(shibaDir)) {
    mkdirSync(shibaDir, { recursive: true });
  }

  // Generate all files in parallel
  const [user, feedback, project, skills, context] = await Promise.all([
    generateUserFile(opts.projectPath),
    generateFeedbackFile(opts.projectPath),
    generateProjectFile(opts.projectPath),
    generateSkillsFile(opts.projectPath),
    generateContextFile(opts.projectPath),
  ]);

  const files: [string, string][] = [
    ["user.md", user],
    ["feedback.md", feedback],
    ["project.md", project],
    ["skills.md", skills],
    ["context.md", context],
  ];

  let totalMemories = 0;
  const written: string[] = [];

  for (const [filename, content] of files) {
    const filepath = resolve(shibaDir, filename);
    writeFileSync(filepath, content, "utf-8");
    written.push(filename);
    // Count memories (rough: count lines starting with "- **")
    totalMemories += (content.match(/^- \*\*/gm) || []).length;
  }

  // Write a .gitignore in .shiba/ to avoid committing generated files
  const gitignorePath = resolve(shibaDir, ".gitignore");
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, "# Auto-generated by Shiba Memory\n*\n", "utf-8");
  }

  return { dir: shibaDir, files: written, totalMemories };
}
